[feature] Docker
intellisys/tribe-kitchen pull request #1
Opened 2017-07-08 13:14 UTC by TheGamer1973

## Status
**READY**

## Migrations
NO

## Description
Creating Dockerfile and Github Templates for the project.

2017-07-09 13:55 UTC, Eduardoveras approved these changes

2017-07-10 13:15 UTC, yimialmonte approved these changes

2017-07-11 14:17 UTC, jsainthilaire commented
@TheGamer1973 why don't we just build and push the docker image so people just need to pull an already created image, this will help with consistency and save a step in the dev process?

2017-07-11 14:17 UTC, jsainthilaire requested changes
@TheGamer1973 why don't we just build and push the docker image so people just need to pull an already created image, this will help with consistency and save a step in the dev process?

2017-07-11 14:17 UTC, jsainthilaire commented on Dockerfile
> +RUN npm install --quiet --global \ vue-cli && apt-get update -qq && apt-get install git -y -V
why are we running npm install twice?

2017-07-11 14:17 UTC, jsainthilaire commented on Dockerfile
> +WORKDIR /usr/src/app
we could use an app or src directly because mounting a folder structure following /usr will be confusing

2017-07-11 14:19 UTC, jsainthilaire commented
also before merging you should squash and clean these commits.

2017-07-11 19:58 UTC, TheGamer1973 commented
As for the Squash, after approving the commit Github gives the approach to Squash and Merge or should I do it before?

2017-07-11 20:01 UTC, TheGamer1973 commented
Made some changes as requested.

2017-07-11 20:56 UTC, jsainthilaire commented
I will approve this for now, but the process needs to be rethought.

2017-07-11 20:56 UTC, jsainthilaire approved these changes

2017-07-11 23:14 UTC, merged